kind: CronJob
apiVersion: batch/v1
metadata:
  name: nb-culler
  labels:
    component.opendatahub.io/name: nb-culler
    opendatahub.io/component: 'true'
    opendatahub.io/modified: 'false'
spec:
  schedule: '0 7 * * *'
  startingDeadlineSeconds: 200
  concurrencyPolicy: Replace
  suspend: false
  jobTemplate:
    metadata:
      labels:
        component.opendatahub.io/name: nb-culler
        opendatahub.io/component: 'true'
    spec:
      template:
        metadata:
          labels:
            component.opendatahub.io/name: nb-culler
            opendatahub.io/component: 'true'
            parent: nb-culler
        spec:
          restartPolicy: Never
          serviceAccountName: ope-notebook-culler
          schedulerName: default-scheduler
          terminationGracePeriodSeconds: 30
          securityContext: {}
          containers:
            - name: oc-cli
              image: >-
                registry.redhat.io/openshift4/ose-cli@sha256:25fef269ac6e7491cb8340119a9b473acbeb53bc6970ad029fdaae59c3d0ca61
              command: ["/bin/bash", "-c", "--"]
              args:
              - |
                  #threshold to stop running notebooks. Currently set to 24 hours
                  cutoff_time=86400
                  current_time=$(date +%s)
                  notebooks=$(oc get notebooks -n ope-rhods-testing-1fef2f -o jsonpath='{range .items[?(@.status.containerState.running)]}{.metadata.name}{" "}{.metadata.namespace}{" "}{.status.containerState.running.startedAt}{"\n"}{end}')
                  if [ -z "$notebooks" ]; then
                      echo "No running notebooks found"
                      exit 0
                  fi                    
                  # Loop through each notebook
                  while read -r nb ns ts; do
                    timestamp=$(date -d $ts +%s)
                    difference=$((current_time - timestamp))
                    if [ $difference -gt $cutoff_time ]; then
                      echo "$nb is more than 24 hours old, stopping the notebook"
                      oc patch notebook $nb -n $ns --type merge -p '{"metadata":{"annotations":{"kubeflow-resource-stopped":"'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'"}}}'
                    fi
                  done <<< "$notebooks"
              resources:
                limits:
                  memory: 800Mi
                requests:
                  memory: 400Mi
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: IfNotPresent
          serviceAccount: ope-notebook-culler
          dnsPolicy: ClusterFirst
  successfulJobsHistoryLimit: 7
  failedJobsHistoryLimit: 7
  