kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: multiple-ns-group-sync
subjects:
  - kind: ServiceAccount
    name: multiple-ns-group-sync
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
