kind: Deployment
apiVersion: apps/v1
metadata:
  name: assign-class-label-webhook
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: assign-class-label-webhook
        webhook: "true"
    spec:
      containers:
        - name: assign-class-label
          image: quay.io/rh-ee-istaplet/ope-webhooks:assign-class-label-webhook
          imagePullPolicy: Always
          ports:
            - containerPort: 443
          volumeMounts:
            - name: cert
              mountPath: /certs
              readOnly: true
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            # EDIT VALUE HERE BEFORE RUNNING, must be comma separated
            - name: RHOAI_CLASS_GROUPS
              value: "cs210,cs599-pmpp"
      serviceAccountName: webhook-sa
      volumes:
        - name: cert
          secret:
            secretName: webhook-cert
