kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  # When running for multiple classes, to avoid crb conflicts, change name
  name: group-sync
subjects:
  - kind: ServiceAccount
    name: group-sync
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: group-sync
